name: whatchamacallit
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas==2.0.3
  - pip==23.2.1
  - fastapi==0.101.1
  - uvicorn==0.23.2
  - pymongo==4.4.1
  - pylint==2.17.5
  - black==23.7.0
  - python-dotenv==0.21.0
  - pip:
    - google-cloud-speech==2.21.0
